name: PHPStan

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'
      - '.github/workflows/phpstan.yml'
  pull_request:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'
      - '.github/workflows/phpstan.yml'

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v4
        with:
          php-version: '8.3'
          coverage: none
          tools: phpstan,composer-dependency-analyser

      - name: Remove development dependencies
        run: |
          jq -r '."require-dev" | keys[]' composer.json \
            | xargs -- composer remove --no-interaction --dev --no-update --no-plugins --no-scripts

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run PHPStan
        run: phpstan

      - name: Run Composer Dependency Analyser
        run: composer-dependency-analyser
